# Generated by Django 4.0.6 on 2022-09-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_emision', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Recibos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_emision', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='reclamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_emision', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
                ('link', models.CharField(max_length=2000)),
            ],
        ),
    ]
